# Introduction to NumPy

NumPy is a Python package and it stands for numerical python

Fundamental package for numerical computations in Python

Supports N-dimensional array objects that can be used for processing multidimensional data

Supports different data-types


# Array

An array is a data structure that stores values of same data type

Lists can contain values corresponding to different data types

Arrays in python can only contain values corresponding to same data type



# NumPy Array

•	A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers

•	The number of dimensions is the rank of the array

•	The shape of an array is a tuple of integers giving the size of the array along each dimension

# Creation of array

To create numpy array, we first need to import the numpy package:

In [2]:
import numpy as np

Single-dimensional Numpy Array:

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(type(a)) 

<class 'numpy.ndarray'>


Multi-dimensional Array

In [5]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


# Python NumPy Operations

# ndim:
You can find the dimension of the array, whether it is a two-dimensional array or a single dimensional array.

In [6]:
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


# itemsize:
You can calculate the byte size of each element.

In [7]:
import numpy as np
a = np.array([(1,2,3)])
print(a.itemsize)

4


# dtype:
You can find the data type of the elements that are stored in an array. 

In [8]:
import numpy as np
a = np.array([(1,2,3)])
print(a.dtype)

int32


# size and shape of the array using ‘size’ and ‘shape’ function 

In [9]:
import numpy as np
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


# reshape:
Reshape is when you change the number of rows and columns which gives a new view to an object. 

In [10]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)


[[ 8  9 10]
 [11 12 13]]


In [11]:
a=a.reshape(3,2)
print(a)

[[ 8  9]
 [10 11]
 [12 13]]


# slicing:Slicing is basically extracting particular set of elements from an array. 

In [10]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [1]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])#Get 2nd index element from all rows, includig zero

[3 5]


Here colon represents all the rows, including zero. Now to get the 2nd element, we’ll call index 2 from both of the rows which gives us the value 3 and 5 respectively.

# max/ min

In [13]:
import numpy as np
 
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


Suppose you want to calculate the sum of all the columns, then you can make use of axis.

In [14]:
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))

[4 6 8]


In [15]:
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=1))

[ 6 12]


# Square Root & Standard Deviation

In [16]:
import numpy as np
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))  #square root of all the elements are printed. 

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [17]:
print(np.std(a))

1.2909944487358056


standard deviation is printed for the above array i.e how much each element varies from the mean value of the python numpy array.

# Addition Operation

In [18]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)

[[ 2  4  6]
 [ 6  8 10]]


In [19]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)

[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Vertical & Horizontal Stacking

if you want to concatenate two arrays and not just add them, you can perform it using two ways – vertical stacking and horizontal stacking.

In [20]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [21]:
print(np.hstack((x,y)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [22]:
import numpy as np
np.random.seed(0)  # seed for reproducibility 

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run

In [26]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


dtype, the data type of the array

In [27]:
print("dtype:", x3.dtype)

dtype: int32


itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array

In [28]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


# Reshaping of Arrays

In [29]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [31]:
# reshaping the ndarray
a. shape = (3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
#  Reshape  function  to  resize  an  array
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [34]:
r = range(24)

In [35]:
print(r)

range(0, 24)


In [36]:
# An array of evenly spaced numbers
a = np.arange(24) 
print(a) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [37]:
print(a.ndim)

1


In [38]:
# Reshaping the array a
b = a.reshape(6,4,1) 
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


numpy.itemsize

This array attribute returns the length of each element of array in bytes.

In [39]:
#  dtype  of  array  is   int8  (1 byte)
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


In [40]:
#  dtype  of  array  is   float 32  (4 bytes)
x = np.array([1,2,3,4,5], dtype = np.float32)
print(x.itemsize)

4


In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [41]:
x2 = np.random.randint(10, size=(3, 4))

In [42]:
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [43]:
x2[0, 0]

4

In [44]:
x2[2, 0]

5

In [45]:
x2[2, -1]

1

# NumPy Arithmetic operations

In [46]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x)

[[1. 2.]
 [3. 4.]]


In [47]:
y = np.array([[5,6],[7,8]], dtype=np.float64) 
print(y)

[[5. 6.]
 [7. 8.]]


In [48]:
print(x + y) 

[[ 6.  8.]
 [10. 12.]]


In [49]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [50]:
print(x - y) 

[[-4. -4.]
 [-4. -4.]]


In [51]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [52]:
print(x * y) 

[[ 5. 12.]
 [21. 32.]]


In [53]:
print(np.multiply(x, y)) 

[[ 5. 12.]
 [21. 32.]]


In [54]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [55]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [56]:
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]


In [57]:
print(x / y) 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [58]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [59]:
print (np . sum(x) ) #Compute sum of all elements

10.0


In [60]:
print (np . sum(x,  axis=0) ) #Compute sum of all columns

[4. 6.]


In [61]:
print (np . sum(x,  axis=1) )#Compute sum of all rows

[3. 7.]


# Concatenation of arrays

In [62]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [63]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]
