# Scipy

SciPy is a very useful scientific library and has very fast computational power. It has functionalities to perform linear algebraic operations. We perform all these operations on the input object and it gives the array as output.

SciPy has all the features included in the NumPy linear algebra module and some extended functionality.

The linalg module has specific functions for different types of operations.

Linear Algebra

Determinant of a Matrix

In [4]:
# import numpy library
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [5]:
# importing linalg function from scipy
from scipy import linalg
  
# Compute the determinant of a matrix
linalg.det(A)

3.0

Eigen values and eigen vectors of this matrix

In [7]:
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)

[15.55528261+0.j -1.41940876+0.j -0.13587385+0.j]


In [8]:
print(eigen_vectors)

[[-0.24043423 -0.67468642  0.51853459]
 [-0.54694322 -0.23391616 -0.78895962]
 [-0.80190056  0.70005819  0.32964312]]


Solving systems of linear equations

In [10]:
v = np.array([[2],[3],[5]])
print(v)


[[2]
 [3]
 [5]]


In [11]:
s = linalg.solve(A,v)
print(s)

[[-2.33333333]
 [ 3.66666667]
 [-1.        ]]


Exponential and Trigonometric Functions:

SciPy’s Special Function package provides a number of functions through which you can find exponents and solve trigonometric problems.

In [12]:
from scipy import special
a = special.exp10(3)
print(a)
 
b = special.exp2(3)
print(b)
 
c = special.sindg(90)
print(c)
 
d = special.cosdg(45)
print(d)

1000.0
8.0
1.0
0.7071067811865475
